version: '3.8'
services:
  api-epi-core:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mysql://mysql:ggruRGLuLMNej5DmSkVVZ28rhiZ2r4M3pP2YKRmsZ02zlsPal4T0lMflvreJjcTS@85.31.62.75:5432/epi"
      NODE_ENV: "production"
      CORS_ORIGIN: "*"
