services:
  api-epi-core:
    container_name: api-epi-core
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV:-production}
      - ENV=${ENV:-prod}
      - PORT=${PORT:-3000}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
      - API_CONSULTA_URL=${API_CONSULTA_URL}
      - API_KEY=${API_KEY}
      - API_TOKEN=${API_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${PORT:-3000}/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
