version: '3.8'
services:
  api-epi-core:
    container_name: api-epi-core
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - ENV=${ENV}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
