version: '3.8'

services:
  api-epi-core:
    image: ghcr.io/sistema-epi/api-epi-core:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - ENV=${ENV}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - API_CONSULTA_URL=${API_CONSULTA_URL}
      - API_KEY=${API_KEY}
      - API_TOKEN=${API_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./logs:/usr/src/app/logs
