services:
  api-epi-core:
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    container_name: api-epi-core
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - ENV=${ENV}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - API_CONSULTA_URL=${API_CONSULTA_URL}
      - API_KEY=${API_KEY}
      - API_TOKEN=${API_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
    # ports:
    #   - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - ./logs:/usr/src/app/logs
