version: '3.8'
services:
  app-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mysql://user:password@mysql-container:3306/epi"
      NODE_ENV: "production"
      CORS_ORIGIN: "*"
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: epi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
