version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: epi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - epi-network
  api:
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      DATABASE_URL: "mysql://root:root_password@mysql:3306/epi"
      NODE_ENV: "production"
      CORS_ORIGIN: "*"
    depends_on:
      - mysql
    networks:
      - epi-network

networks:
  epi-network:
    driver: bridge

volumes:
  mysql_data:
